### PR TITLE
ES6+ updates - Initial commit (still being tested)

### PR DESCRIPTION
**Pull request by MateMalice**
Hi,

I was looking to use this package for work & am a big fan of all the functionality it has.

However, I'm looking to use the package on NodeJS v10.15.2 LTS, which has introduced a number of ES6 features and deprecated the use of the new Buffer() constructor for security reasons (see https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/). Given how long the deprecation warning has been in place, I don't think it'll be too long before code using the old Buffer methods will no longer work.

As such, I took it upon myself to change the code dealing with buffers & to refactor the code to use ES6 classes and other features that are supported by newer versions of Node.

This fork contains my updates - they've passed my preliminary tests, but I'll still be doing more testing in the next few days.

In the meantime, I've put in this pull request in case any package maintainers still working on this project want to contribute. :-)

M

### CODE REVIEW

**Comment by Pranav-Dakshina** [comment]
Hi @MatejMalicek,

Appreciate the effort. Looks good for my side. 
I have added you as a collaborator, please feel free to merge the pull request when your testing is done.

Thanks,
Pranav

**Comment by MateMalice** [comment]
Hi Pranav,

Thank you for adding me & my apologies for the late response - I was at a hackercon last weekend and spent a fair bit of time preparing!

After doing further testing, I realised that there was an issue with how the newer dependencies (namely the new MailParser) handled Buffers - they also appear to have changed many of the functions for dealing with attachments. They also introduced a simpleParser function, which is easier to implement & produces a Map object with all the relevant details. However, simpleParser does not stream attachments, rather it saves them in Buffers. For my purposes, this is preferable, as I do not have large attachments to process. For my business case, streaming is not actually a substantial feature, as I do have some security concerns about streaming potentially-untrusted content.

They still have the MailParser constructor (as opposed to the simpleParser), but it appears to be used quite differently to how the previous versions used it. This means that using this larger function (which provides streaming capabilities) will require me to make substantial changes to the previous code. In the interests of saving time, I have committed a new version to my fork that uses simpleParser, which provides most of the functionality of the previous version, less attachment streaming.

I am happy to keep my fork separate and then merge it when I add streaming capabilities (I'll do this in the coming weeks), or I can merge the two now if you would prefer. 

Please let me know. :-)

Cheers,

Matej

**Comment by Pranav-Dakshina** [comment]
Hey @MatejMalicek,

Sorry for the late reply, You can go ahead and merge the two now. :)

Thanks,
Pranav

**Comment by MateMalice** [comment]
My apologies about late response too - been a busy week!

I've merged the two now & have published the current version on NPM as mail-listener5. 

I'll work on adding streaming & more attachment-handling features when I get the time :-)

Thanks,
Matej

**Pull request merged**
